### PR TITLE
add host option when not using ssh tunnel

### PR DESCRIPTION
**Pull request by sebcbi1**
fix connection to host without ssh tunnel and use -h parameter in cli

for example : 

{
  "connection": {
          "server": "192.168.1.111",
          "port": 5432,
          "binary": "/usr/bin/psql",
          "user": "user",
          "password": "",
          "database": "dbname",
          "is_remote": true,
          "db_type": "postgresql"
  }
}

this may break your custom config/workflow

### CODE REVIEW

**Comment by mrvaita** [comment]
This is a bit tricky. Did you have the chance to test it? In my development environment I have not possibility to run such a test. In your example your connection information have the option `is_remote` set to `true`. This will automatically enable the `ssh` command and this is not what you want in this case I think.

**Comment by mrvaita** [comment]
Overall I think this is a nice feature to add. What I also think is that in case we merge this PR the `is_remote` field should be changed to something like `ssh` to avoid confusion.

**Comment by sebcbi1** [comment]
I suppose that port are not opened on your db servers and they are listening from localhost , that's why you rely on ssh tunnel. i was little confused how to setup the config and discover that host/server name was never had as an argument to the cli . which is the common use case. 

maybe you could use a similar config file as [sql-language-server](https://github.com/joe-re/sql-language-server#project-configuration-file) or read those files . they have option for ssh tunnel in config file . and so have lsp and sqlrun be configured and run together

**Comment by mrvaita** [comment]
It is exactly like you said. Basically the `server` option is only used for the ssh command. I have added some changes to your PR and it looks like I was able to keep the functionality that you added as well as the ssh connection. Shall I push those changes and you perhaps have a look at it?

**Comment by sebcbi1** [comment]
sure . you can push in a branch

**Comment by mrvaita** [comment]
Thanks. You can find the changes [here](https://github.com/mrvaita/sqlrun.nvim/tree/mrvaita-feature-add-host-connection-string). I could not test your feature part as I cannot. But you can try it out. Basically the `server` field is used as database host if the `ssh` option is false. Feel free to add the changes to your PR if you like what I suggested

**Comment by sebcbi1** [comment]
It's all good for me . Thanks . I think you could merge in main

**Comment by mrvaita** [comment]
Thanks. I will do.

**Comment by sebcbi1** [comment]
you didn't merge your branch so commit commit 07449f4fccb5aa659e5402499dcc2a82ccf07de9  is not in main

**Comment by mrvaita** [comment]
You are right. I got confused. I wanted to keep your commit in the history as well but I forgot to merge my branch with yours first. Sorry it it the first time that I deal with a contribution and I need to learn how to do it properly.

**Comment by mrvaita** [comment]
It should be fixed now

**Pull request merged**
